"""create all 12 identity and analytics tables

Revision ID: 4116c50c85ec
Revises: fff8e2635e48
Create Date: 2026-09-02 08:08:17.364027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4116c50c85ec'
down_revision: Union[str, Sequence[str], None] = 'fff8e2635e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pseudonymous_id', sa.UUID(), nullable=False),
    sa.Column('deployment_type', sa.String(), nullable=False),
    sa.Column('hardship_level', sa.SmallInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.CheckConstraint('hardship_level BETWEEN 1 AND 5', name='ck_deployments_hardship_level_range'),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_deployments_pseudonymous_id'), 'deployments', ['pseudonymous_id'], unique=False, schema='analytics')
    op.create_table('duty_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pseudonymous_id', sa.UUID(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('shift_type', sa.String(), nullable=False),
    sa.Column('duty_hours', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.CheckConstraint("shift_type IN ('day', 'night', 'extended')", name='ck_duty_records_shift_type_valid'),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_duty_records_pseudonymous_id'), 'duty_records', ['pseudonymous_id'], unique=False, schema='analytics')
    op.create_table('leave_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pseudonymous_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_leave_records_pseudonymous_id'), 'leave_records', ['pseudonymous_id'], unique=False, schema='analytics')
    op.create_table('risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pseudonymous_id', sa.UUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('probability_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('calibrated_score', sa.SmallInteger(), nullable=False),
    sa.Column('risk_category', sa.String(), nullable=False),
    sa.Column('contributing_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rule_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("risk_category IN ('low', 'moderate', 'high', 'critical')", name='ck_risk_category_valid'),
    sa.CheckConstraint('calibrated_score BETWEEN 0 AND 100', name='ck_risk_score_range'),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_risk_scores_pseudonymous_id'), 'risk_scores', ['pseudonymous_id'], unique=False, schema='analytics')
    op.create_table('training_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pseudonymous_id', sa.UUID(), nullable=False),
    sa.Column('training_date', sa.Date(), nullable=False),
    sa.Column('hours_committed', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_training_records_pseudonymous_id'), 'training_records', ['pseudonymous_id'], unique=False, schema='analytics')
    op.create_table('transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pseudonymous_id', sa.UUID(), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_transfers_pseudonymous_id'), 'transfers', ['pseudonymous_id'], unique=False, schema='analytics')
    op.create_table('wellness_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pseudonymous_id', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('mood_score', sa.SmallInteger(), nullable=True),
    sa.Column('sleep_quality_score', sa.SmallInteger(), nullable=True),
    sa.Column('stress_self_rating', sa.SmallInteger(), nullable=True),
    sa.Column('help_requested', sa.Boolean(), nullable=False),
    sa.Column('free_text_note_enc', sa.LargeBinary(), nullable=True),
    sa.CheckConstraint('mood_score BETWEEN 1 AND 5', name='ck_wellness_mood_range'),
    sa.CheckConstraint('sleep_quality_score BETWEEN 1 AND 5', name='ck_wellness_sleep_range'),
    sa.CheckConstraint('stress_self_rating BETWEEN 1 AND 10', name='ck_wellness_stress_range'),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_wellness_assessments_pseudonymous_id'), 'wellness_assessments', ['pseudonymous_id'], unique=False, schema='analytics')
    op.create_table('units',
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('unit_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('unit_id'),
    schema='identity'
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('risk_score_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("severity IN ('info', 'moderate', 'high', 'critical')", name='ck_alerts_severity_valid'),
    sa.CheckConstraint("status IN ('open', 'acknowledged', 'resolved')", name='ck_alerts_status_valid'),
    sa.ForeignKeyConstraint(['risk_score_id'], ['analytics.risk_scores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('risk_score_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_type', sa.String(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['risk_score_id'], ['analytics.risk_scores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_table('personnel',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('service_number', sa.String(), nullable=False),
    sa.Column('name_enc', sa.LargeBinary(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('pseudonymous_id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['identity.units.unit_id'], ),
    sa.PrimaryKeyConstraint('person_id'),
    sa.UniqueConstraint('pseudonymous_id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_personnel_service_number'), 'personnel', ['service_number'], unique=True, schema='identity')
    op.create_table('interventions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('recorded_by_person_id', sa.UUID(), nullable=False),
    sa.Column('intervention_type', sa.String(), nullable=False),
    sa.Column('notes_enc', sa.LargeBinary(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['analytics.alerts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.CheckConstraint("role IN ('personnel', 'welfare_officer', 'admin')", name='ck_user_roles_role_valid'),
    sa.ForeignKeyConstraint(['person_id'], ['identity.personnel.person_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles', schema='identity')
    op.drop_table('interventions', schema='analytics')
    op.drop_index(op.f('ix_identity_personnel_service_number'), table_name='personnel', schema='identity')
    op.drop_table('personnel', schema='identity')
    op.drop_table('recommendations', schema='analytics')
    op.drop_table('alerts', schema='analytics')
    op.drop_table('units', schema='identity')
    op.drop_index(op.f('ix_analytics_wellness_assessments_pseudonymous_id'), table_name='wellness_assessments', schema='analytics')
    op.drop_table('wellness_assessments', schema='analytics')
    op.drop_index(op.f('ix_analytics_transfers_pseudonymous_id'), table_name='transfers', schema='analytics')
    op.drop_table('transfers', schema='analytics')
    op.drop_index(op.f('ix_analytics_training_records_pseudonymous_id'), table_name='training_records', schema='analytics')
    op.drop_table('training_records', schema='analytics')
    op.drop_index(op.f('ix_analytics_risk_scores_pseudonymous_id'), table_name='risk_scores', schema='analytics')
    op.drop_table('risk_scores', schema='analytics')
    op.drop_index(op.f('ix_analytics_leave_records_pseudonymous_id'), table_name='leave_records', schema='analytics')
    op.drop_table('leave_records', schema='analytics')
    op.drop_index(op.f('ix_analytics_duty_records_pseudonymous_id'), table_name='duty_records', schema='analytics')
    op.drop_table('duty_records', schema='analytics')
    op.drop_index(op.f('ix_analytics_deployments_pseudonymous_id'), table_name='deployments', schema='analytics')
    op.drop_table('deployments', schema='analytics')
    # ### end Alembic commands ###
